config/routes.rb
Rails.application.routes.draw do

get 'badges' => 'badges#index'
  devise_for :users, controllers: { :registrations => "users/registrations", :invitations => 'users/invitations', sessions: "users/sessions" }

  root 'troops#home'

  get 'newsletters/new' => 'newsletters#new'
  post 'newsletters' => 'newsletters#create'
  get 'newsletters/:id' => 'newsletters#show'

resources :user_badges do
  get :autocomplete_badge_name, :on => :collection
end
resources :events, :only => [:new, :create] do
  get :autocomplete_badge_name, :on => :collection
end



#-------Troop-Specific Routes----------
# get 'user_badges/new' => 'user_badges#new'
# get 'user_badges' => 'user_badges#index'
  #get '/troops' => 'troops#index'
  get 'troops/new' => 'troops#new'
  post '/troops' => 'troops#create'
  get 'troops/search/name' => 'troops#name_search'
  get 'troops/search/location' => 'troops#location_search'
  get 'troops/:id' => 'troops#show', :as => :troop_show

  get '/troops/:troop_id/members' => 'troop_users#index', :as => :troop_user

  # get '/troops' => 'troops#index'
  # get 'troops/new' => 'troops#new'
  # post '/troops' => 'troops#create'

  # get '/troops/:troop_id/users/new' => 'users/invitations#new'
  # post '/troops/:troop_id/users' => 'users#create'
  # get '/troops/:troop_id/users/:id' => 'users#show', 

  #get 'troops/edit/:id' => 'troops#edit'
  #patch 'troops/update/:id' => 'troops#update'

#---Routes for Individual Users -----
  get '/users/:id' => 'users#show', :as => :user_show
  get '/users/edit/:id' => 'users#edit', :as => :edit_user
  patch '/users/update/:id' => 'users#update', :as => :update_user
  delete '/users/destroy' => 'troop_users#destroy'



#-------Events---------------
  get 'events' => 'events#index', :as => :events_index
  get 'events/new'
  get 'events/advanced_search' => 'events#advanced_search'
  get 'events/search' => 'events#search_results'
  get 'events/a_search' => 'events#advanced_search_results'
   get 'events/:id' => 'events#show', :as => :event
  get 'events/:id/edit' => 'events#edit'
  patch 'events/:id' => 'events#update'
  post 'events' => 'events#create'
  delete 'events/:id/delete' => 'events#delete'


  get 'troop_events/new' => 'troop_events#new'
  get 'troop_events/:troop_id/new_event' => 'troop_events#new_event', as: 'new_troop_event'
  post 'troop_events/new_event' => 'troop_events#create_event'
  post 'troop_events' => 'troop_events#create'
  get 'troop_events/:id' => 'troop_events#show', as: 'troop_event'

  post 'photos/:photoable_id/:photoable_type' => 'photos#create'
  delete 'photos/:photoable_id/:page_for_redirect/:photo_id' => 'photos#delete'

  get 'troops/:troop_id/photos' => 'photos#individual_troop', as: 'troop_photos'

  # get '/agenda' => 'agenda#index', :as => :troop_agenda
  # get '/agenda/new' => 'agenda#new', :as => :new_troop_agenda
  # post '/agenda' => 'agenda#create'
  # get '/agenda/:id' => 'agenda#show', :as => :agenda_show
  # get '/agenda/edit/:id' => 'agenda#edit'
  # patch '/agenda/update/:id' => 'agenda#update'
  # delete '/agenda/destroy' => 'agenda#destroy'

  get 'agenda/new' => 'agenda#new'
  post 'agendas' => 'agenda#create'
  get 'agenda/:id' => 'agenda#show', as: 'agenda_show'
  get 'agenda' => 'agenda#index'

    
  get 'skills' => 'skills#index'
  get 'skills/:id/index' => 'skills#category_index'
  get 'skills/:id'  => 'skills#show'

  #-------Troop Blog---------------
  get '/troops/:id/troop_blog/new' => 'troop_blogs#new',  :as => 'troop_blog_new'
  post '/troops/:id/troop_blogs' => 'troop_blogs#create', :as => 'troop_blogs'
  get 'troops/:id/troop_blog' => 'troop_blogs#index', :as => 'troop_blog_index'


end

app/models/troop_blog.rb
class TroopBlog < ActiveRecord::Base
  belongs_to :troop

  mount_uploader :photo, ProfilePhotoUploader

  validates_presence_of :headline
  validates_presence_of :body

  def self.homepage_news_feed
    order(created_at: :desc).limit(3)
  end

  def formatted_date
    "#{created_at.month}/#{created_at.day}/#{created_at.year}"
  end

  def find_troop_name(troop_id)
    Troop.find(troop_id).name
  end

  def self.troop_news_feed(troop_id)
    TroopBlog.where(troop_id: troop_id).order(created_at: :desc).limit(5)
  end

  def self.sidebar_news_feed(troop_id)
    TroopBlog.where(troop_id: troop_id).order(created_at: :desc).limit(4)
  end

  def self.full_news_feed(troop_id)
    TroopBlog.where(troop_id: troop_id).order(created_at: :desc)
  end

  def self.large_sidebar_news_feed(troop_id)
    TroopBlog.where(troop_id: troop_id).order(created_at: :desc).limit(10)
  end

end

app/controllers/troop_blogs_controller.rb
class TroopBlogsController < ApplicationController
  before_action :set_troop
  before_action :authenticate_user!, only: [:new]

  def index
    @newsletter = Newsletter.all.last
    @news = TroopBlog.troop_news_feed(params[:id]).paginate(page: params[:page], per_page: 10)
    @sidebar_news = TroopBlog.large_sidebar_news_feed(params[:id])   
  end

  def new
    unless current_user.admin_privileges < 50
      redirect_to(:back)
    end
    @troop_blog = TroopBlog.new
    @troop_blog.troop_id = params[:id]
  end

  def create
    @troop_blog = TroopBlog.new(troop_blog_params)
    respond_to do |format|
      if @troop_blog.save
        format.html { redirect_to "/troops/#{@troop_blog.troop_id}", notice: 'This post has been added to your blog' }
      else
        format.html { render action: 'new' }
      end
    end
  end

  def destroy
  end



  private
  def set_troop
    @troop = Troop.find(params[:id])
  end

  def troop_blog_params
    params.require(:troop_blog).permit(:troop_id, :headline, :body, :photo )
  end

  def set_user
    @user = User.find(params[:id])
  end

end

app/views/troop_blogs/index.html.erb
<%=render partial: 'layouts/banner', locals: {:name => "#{@troop.name} blog", :left_option => "Troop Hub: The Social Media Site for Girl Scouts", :right_option => "Troop Number: #{@troop.number}" }%>     


      <div class="inner-page padd">
      
        <!-- Blog Start -->
          
        <div class="blog">
          <div class="container">
            <div class="row">

              <div class="col-md-8">
                <!-- The new post done by user's all in the post block -->
                <div class="blog-post">
                  <%= link_to '<< Return to Troop Home Page', troop_show_path(@troop) %><br><br>
                  <!-- Entry is the one post for each user -->
                <% @news.each do |article| %>
                  <div class="entry">
                    <!-- Post Images -->
                    <div class="blog-img pull-left">
                      <img src="<%= article.photo %>" class="img-responsive img-thumbnail" alt="" />
                    </div>
                    <!-- Meta for this block -->
                    <div class="meta">
                      <i class="fa fa-calendar"></i>&nbsp; <%= article.formatted_date %>
                      <span class="pull-right"><i class="fa fa-comment"></i> <a href="/troops/<%=article.troop_id%>"><%= article.find_troop_name(article.troop_id) %></a></span>
                    </div>
                    <!-- Heading of the  post -->
                    <h3><%= link_to article.headline, troop_blog_index_path %> </h3>
                    <hr /><!-- Horizontal line -->
                    <!-- Paragraph -->
                    <p><%= article.body %></p>
                    <div class="clearfix"></div>
                  </div>
                <% end %>
 
                  <!-- Entry is the one post for each user -->


                  <!-- Pagination -->
          <%= will_paginate @news, renderer: BootstrapPagination::Rails %>
                  <!-- Pagination end-->
                </div>
              </div> <!--/ Main blog column end -->
              <div class="col-md-4">
                <!-- Blog page sidebar -->
                <div class="blog-sidebar">
                  
                    <div class="col-md-12 col-sm-6">
                      <!-- Blog sidebar page widget -->
                      <div class="sidebar-widget">
                        <!-- Widget Heading -->
                        <h4>Recent Posts</h4>
                        <!-- Recent post list -->
                        <ul class="list-unstyled">
                          <% @sidebar_news.each do |article|  %>
                          <li><i class="fa fa-angle-double-right"></i> <%= link_to article.headline, troop_blog_index_path %></li>
                          <% end %>
                        </ul>
                      </div><!--/ Widget end -->
                    </div>
                   
                  </div><!--/ Inner row end -->
                  <% if current_user && current_user.admin_privileges == 0 && current_user.troops.include?(@troop) %>  
                  <div class="blog-sidebar">
                  
                    <div class="col-md-12 col-sm-6">
                      <!-- Blog sidebar page widget -->
                      <div class="sidebar-widget">
                        <!-- Widget Heading -->
                        <h4><%= link_to "Add More News Here >>", troop_blog_new_path(@troop) %></h4>
                        <!-- Recent post list -->
                        
                      </div><!--/ Widget end -->
                    </div>
                   
                  </div><!--/ Inner row end -->
                  <% end %>
                </div><!--/ Page sidebar end -->
              </div>
            </div><!--/ Row end -->
          </div>
        </div>

app/views/troop_blogs/new.html.erb
<%=render partial: 'layouts/banner', locals: {:name => "Add Your Troop", :left_option => "Troop Hub: The Social Media Site for Girl Scouts", :right_option => "Register Your Troop for Troop Hub Here" }%>


      <div class="inner-page padd">
      
        <!-- Single Item Start -->
        
        <div class="single-item">
          <div class="container">
            <!-- Shopping single item contents -->
            <div class="single-item-content">
              <div class="row">
                <div class="col-md-4 col-sm-5">
                  <!-- Product image -->
                  <img class="img-responsive img-thumbnail" src="http://www.justamorous.com/wp-content/uploads/2014/02/Girl-Scout-Cookies.jpg" alt="" />
                </div>
                <div class="col-md-8 col-sm-7">
                  <!-- Heading -->
                  <h3>Add News Article</h3>
                  <%  @troop_blog.errors.full_messages.each do |msg| %>
                    <li><font color="red"><%= msg %></font></li>
                  <% end %>
                  <div class="row">
                    <div class="col-md-7 col-sm-12">
                      <!-- Single item details -->
                      <div class="item-details">
                        <!-- Paragraph -->
                        <p class="text-justify"></p>

                       <%= form_for @troop_blog do |f| %>
                            <label>Troop News:</label>
                            <%= f.hidden_field :troop_id %>

                            <label>Headline:</label>
                            <%= f.text_field :headline, class: "form-control" %></br>

                            <label>News Body:</label>
                            <%= f.text_area :body, class: "form-control", :rows => 15 %>
                         
                            <label>Photo:</label>
                            <%= f.file_field :photo %></br>

                            
                          <button class="btn btn-danger btn-sm show-submit" type="submit">Add News Article</button>
                          <% end %>
                      </div>



                       <div class="table-responsive">
                        <!-- Ordering form -->
                       
                      </div><!--/ Table responsive class end -->
                    </div>
                    
                  </div><!--/ Inner row end  -->
                </div>
              </div>
            </div>
          </div>
        </div>

app/views/troop_blogs/show.html.erb
<%=render partial: 'layouts/banner', locals: {:name => @troop.name, :left_option => "Troop Type: #{@troop.name}", :right_option => "Troop Number: #{@troop.number}" }%>     


      <div class="inner-page padd">
      
        <!-- Blog Start -->
          
        <div class="blog">
          <div class="container">
            <div class="row">
              <div class="col-md-8">
                <!-- The new post done by user's all in the post block -->
                <div class="blog-post">
                  <!-- Entry is the one post for each user -->
                <% @news.each do |article| %>
                  <div class="entry">
                    <!-- Post Images -->
                    <div class="blog-img pull-left">
                      <img src="<%= article.photo %>" class="img-responsive img-thumbnail" alt="" />
                    </div>
                    <!-- Meta for this block -->
                    <div class="meta">
                      <i class="fa fa-calendar"></i>&nbsp; <%= article.formatted_date %>
                      <span class="pull-right"><i class="fa fa-comment"></i> <a href="/troops/<%=article.troop_id%>"><%= article.find_troop_name(article.troop_id) %></a></span>
                    </div>
                    <!-- Heading of the  post -->
                    <h3><a href="blog-single.html"><%= article.headline %> </a></h3>
                    <hr /><!-- Horizontal line -->
                    <!-- Paragraph -->
                    <p><%= article.body %></p>
                    <div class="clearfix"></div>
                  </div>
                <% end %>
 
                  <!-- Entry is the one post for each user -->


                  <!-- Pagination -->
          <%= will_paginate @news, renderer: BootstrapPagination::Rails %>
                  <!-- Pagination end-->
                </div>
              </div> <!--/ Main blog column end -->
              <div class="col-md-3">
                <!-- Blog page sidebar -->
                <div class="blog-sidebar">
                  
                    <div class="col-md-12 col-sm-6">
                      <!-- Blog sidebar page widget -->
                      <div class="sidebar-widget">
                        <!-- Widget Heading -->
                        <h4>Recent Posts</h4>
                        <!-- Recent post list -->
                        <ul class="list-unstyled">
                          <% @sidebar_news.each do |article|  %>
                          <li><i class="fa fa-angle-double-right"></i> <a href="#"><%= article.headline %></a></li>
                          <% end %>
                        </ul>
                      </div><!--/ Widget end -->
                    </div>
                   
                  </div><!--/ Inner row end -->
                </div><!--/ Page sidebar end -->
              </div>
            </div><!--/ Row end -->
          </div>
        </div>