config/routes.rb
Rails.application.routes.draw do

get 'badges' => 'badges#index'
  devise_for :users, controllers: { :registrations => "users/registrations", :invitations => 'users/invitations', sessions: "users/sessions" }

  root 'troops#home'

  get 'newsletters/new' => 'newsletters#new'
  post 'newsletters' => 'newsletters#create'
  get 'newsletters/:id' => 'newsletters#show'

resources :user_badges do
  get :autocomplete_badge_name, :on => :collection
end
resources :events, :only => [:new, :create] do
  get :autocomplete_badge_name, :on => :collection
end



#-------Troop-Specific Routes----------
# get 'user_badges/new' => 'user_badges#new'
# get 'user_badges' => 'user_badges#index'
  #get '/troops' => 'troops#index'
  get 'troops/new' => 'troops#new'
  post '/troops' => 'troops#create'
  get 'troops/search/name' => 'troops#name_search'
  get 'troops/search/location' => 'troops#location_search'
  get 'troops/:id' => 'troops#show', :as => :troop_show

  get '/troops/:troop_id/members' => 'troop_users#index', :as => :troop_user

  # get '/troops' => 'troops#index'
  # get 'troops/new' => 'troops#new'
  # post '/troops' => 'troops#create'

  # get '/troops/:troop_id/users/new' => 'users/invitations#new'
  # post '/troops/:troop_id/users' => 'users#create'
  # get '/troops/:troop_id/users/:id' => 'users#show', 

  #get 'troops/edit/:id' => 'troops#edit'
  #patch 'troops/update/:id' => 'troops#update'

#---Routes for Individual Users -----
  get '/users/:id' => 'users#show', :as => :user_show
  get '/users/edit/:id' => 'users#edit', :as => :edit_user
  patch '/users/update/:id' => 'users#update', :as => :update_user
  delete '/users/destroy' => 'troop_users#destroy'



#-------Events---------------
  get 'events' => 'events#index', :as => :events_index
  get 'events/new'
  get 'events/advanced_search' => 'events#advanced_search'
  get 'events/search' => 'events#search_results'
  get 'events/a_search' => 'events#advanced_search_results'
   get 'events/:id' => 'events#show', :as => :event
  get 'events/:id/edit' => 'events#edit'
  patch 'events/:id' => 'events#update'
  post 'events' => 'events#create'
  delete 'events/:id/delete' => 'events#delete'


  get 'troop_events/new' => 'troop_events#new'
  get 'troop_events/:troop_id/new_event' => 'troop_events#new_event', as: 'new_troop_event'
  post 'troop_events/new_event' => 'troop_events#create_event'
  post 'troop_events' => 'troop_events#create'
  get 'troop_events/:id' => 'troop_events#show', as: 'troop_event'

  post 'photos/:photoable_id/:photoable_type' => 'photos#create'
  delete 'photos/:photoable_id/:page_for_redirect/:photo_id' => 'photos#delete'

  get 'troops/:troop_id/photos' => 'photos#individual_troop', as: 'troop_photos'

  # get '/agenda' => 'agenda#index', :as => :troop_agenda
  # get '/agenda/new' => 'agenda#new', :as => :new_troop_agenda
  # post '/agenda' => 'agenda#create'
  # get '/agenda/:id' => 'agenda#show', :as => :agenda_show
  # get '/agenda/edit/:id' => 'agenda#edit'
  # patch '/agenda/update/:id' => 'agenda#update'
  # delete '/agenda/destroy' => 'agenda#destroy'

  get 'agenda/new' => 'agenda#new'
  post 'agendas' => 'agenda#create'
  get 'agenda/:id' => 'agenda#show', as: 'agenda_show'
  get 'agenda' => 'agenda#index'

    
  get 'skills' => 'skills#index'
  get 'skills/:id/index' => 'skills#category_index'
  get 'skills/:id'  => 'skills#show'

  #-------Troop Blog---------------
  get '/troops/:id/troop_blog/new' => 'troop_blogs#new',  :as => 'troop_blog_new'
  post '/troops/:id/troop_blogs' => 'troop_blogs#create', :as => 'troop_blogs'
  get 'troops/:id/troop_blog' => 'troop_blogs#index', :as => 'troop_blog_index'


end

app/models/event.rb
require 'prime'

class Event < ActiveRecord::Base

  has_many :troop_events
  has_many :troops, through: :troop_events

  has_many :event_badges, dependent: :destroy
  has_many :badges, through: :event_badges, dependent: :destroy

  has_many :event_age_levels, dependent: :destroy
  has_many :age_levels, through: :event_age_levels, dependent: :destroy
  belongs_to :skill

  validates :name, :presence => true 
  validates :skill_id, :presence => true
  validates :season, :presence => true


  def self.find_all_by_name(name)
    where("name like ?", name)
  end

  def self.find_by_search_results_with_too_many_forks(name, skill_id, age_level_ids, badge_ids, season_number)
    seasons = Event.seasons_for_search(season_number.to_i)
    skills = Event.skills_for_search(skill_id)
    badges = Event.badges_for_search(badge_ids)
    ages = Event.ages_for_search(age_level_ids) if age_level_ids

    if (name != "") && seasons.nil? && skills.nil? && age_level_ids.nil? && badge_ids.nil?
      results = Event.find_all_by_name(name.capitalize)
    elsif age_level_ids && (badge_ids != []) && (name != "")
      results = Event.all.joins(:event_age_levels).where(:"event_age_levels.age_level_id" => ages).joins(:event_badges).where(:"event_badges.badge_id" => badges).where("name like ?", name).where(season: seasons, skill: skills).uniq
    elsif age_level_ids && (badge_ids != [])
      results = Event.all.joins(:event_age_levels).where(:"event_age_levels.age_level_id" => ages).joins(:event_badges).where(:"event_badges.badge_id" => badges).where(season: seasons, skill: skills).uniq 
    elsif age_level_ids && (name != "")
      results = Event.all.joins(:event_age_levels).where(:"event_age_levels.age_level_id" => ages).where("name like ?", name).where(season: seasons, skill: skills).uniq
    elsif age_level_ids
      results = Event.all.joins(:event_age_levels).where(:"event_age_levels.age_level_id" => ages).where(season: seasons, skill: skills).uniq 
    elsif (badge_ids != []) && (name != "")
      results = Event.all.joins(:event_badges).where(:"event_badges.badge_id" => badges).where("name like ?", name).where(season: seasons, skill: skills).uniq
    elsif (badge_ids != [])
      results = Event.all.joins(:event_badges).where(:"event_badges.badge_id" => badges).where(season: seasons, skill: skills).uniq 
    elsif (name != "")
      results = Event.where("name like ?", name).where(season: seasons, skill: skills).uniq
    else
      results = Event.where(season: seasons, skill: skills).uniq
    end
    results
  end

  def self.seasons_for_search(searched_season_number)
    seasons = {1 => 'Any', 2 => 'Spring', 3 => 'Summer', 5 => 'Fall', 7 => 'Winter', 49 => 'January', 77 => 'Febuary', 14 => 'March', 4 => 'April', 22 => 'May', 6 => 'June', 9 => 'July', 33 => 'August', 15 => 'September', 25 => 'October', 55 => 'November', 35 => 'December', 245 => 'New Years', 117 => 'Independence Day'}
    season_array = []
    seasons.each do |season_number, season_name|
      if searched_season_number % season_number == 0 || season_number % searched_season_number == 0
        season_array << season_name
      end
    end
    season_array
  end

  def self.badges_for_search(names)
    ids = []
    names.each do |name|
      b = Badge.find_by(name: name)
      ids<< b.id
    end
    ids
  end

  def self.ages_for_search(ages)
    if ages.include?(7.to_s)
      (1...7).each do |x|
        ages << x
      end
    else
      all = true
      (1...7).each do |i|
        if not ages.include?(i.to_s)
          all = false
        end
      end
      if all
        ages << 7
      end
    end
    ages
  end


  def self.skills_for_search(skill_id)
    if skill_id.to_i > 0
      skills = Skill.where(id: skill_id)
    elsif skill_id == "General"
      skills = Skill.where(category: 'GENERAL')
    elsif skill_id == "STEM"
      skills = Skill.where(category: 'STEM')
    elsif skill_id == 'Business Smarts'
      skills = Skill.where(category: 'BUSINESS SMARTS')
    elsif skill_id == "Nature and Ecology"
      skills = Skill.where(category: 'NATURE AND ECOLOGY')
    else
      skills = Skill.all
    end
    skills
  end

  def self.find_by_skill_category(category_name)
    category_name = category_name.gsub("-and-"," & ").gsub("-"," ")
    Event.joins(:skill).where("skills.category like ?", category_name.upcase)
  end


  def self.header_for_advanced_search_results(search_criteria)
    header = "Events"
    if (search_criteria[:name] != "")
      header += " named #{search_criteria[:name]}"
    end
    if (search_criteria[:skill_id].to_i != 0)
      skill = Skill.find(search_criteria[:skill_id]).name
      header += " related to #{skill}"
    elsif (search_criteria[:skill_id] != "Any")
      header += " related to #{search_criteria[:skill_id]}"
    else
      header += " related to Any Category"
    end
    if (search_criteria[:age_level_ids])
      ages = " for"
      search_criteria[:age_level_ids].each_with_index do |age_level_id, i|
        if (i == 0)
          name = AgeLevel.find(age_level_id).name
          ages+= " #{name.pluralize}"
        else
          name = AgeLevel.find(age_level_id).name
          ages+= " or #{name.pluralize}"
        end
      end
      header += "#{ages}"
    end
      header += Event.seasons_for_header(search_criteria[:season])
    if (search_criteria[:badge_ids] != "")
      badges = Event.badges_for_search_result_header(search_criteria[:badge_ids])
      header += " giving #{badges}"
    end
    header
  end

  def self.badges_for_search_result_header(badge_names)#this method and one above should be in controller
    badge_names_array = badge_names.split(",") #this and next three lines of code is taken from create event controller. This should either be abstraced or ask emma if autocomplete will allow us to save data from this field in array
    badge_string = ""
    badge_names_array.each_with_index do |b, i|
      if (i == (badge_names_array.length - 1) && badge_names_array.length != 1 && badge_names_array.length != 2)
        badge_string += "or #{b} badges"
      elsif (badge_names_array.length != 1 && badge_names_array.length != 2)
        badge_string += "#{b}, "
      elsif  badge_names_array.length != 2
        badge_string += "a #{b} badge"
      elsif i != (badge_names_array.length - 1)
        badge_string+=b
      else
        badge_string += " or #{b} badges"
      end
    end
    " badges"
    badge_string
  end

  def self.seasons_for_header(number)
    seasons = ""

    lookup_hash = {1 => 'Any', 2 => 'Spring', 3 => 'Summer', 5 => 'Fall', 7 => 'Winter', 49 => 'January', 77 => 'Febuary', 14 => 'March', 4 => 'April', 22 => 'May', 6 => 'June', 9 => 'July', 33 => 'August', 15 => 'September', 25 => 'October', 55 => 'November', 35 => 'December', 245 => 'New Years', 117 => 'Independence Day'}
    number = number.to_i
    factors = Prime.prime_division(number)
    sum = 0
    factors.each do |array|
        sum+=array[1]
      end
    
    if sum == 0
      seasons+= " during any season"
    elsif sum == 1
      seasons+= " during the #{lookup_hash[number]}"
    elsif sum == 2
      seasons += " in the month of #{lookup_hash[number]}"
    else
      seasons += " on #{lookup_hash[number]}"
    end
    seasons
  end

end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < ::Devise::RegistrationsController
  # before_filter :configure_permitted_parameters, :only => [:create]
  include UsersHelper
  before_filter :configure_permitted_parameters, :only => [:create]
  
  def new
    @skills = Skill.all
    super
  end

  def edit
    @skills = Skill.all
  end
  

  def update
  end

  def create 
    sanitize_params_by_role 
    build_resource(sign_up_params)
    resource_saved = resource.save
    yield resource if block_given?
    if resource_saved
    add_skills_to_adults(resource.id, skills_params[:skill_ids], skills_params[:descriptions]) unless skills_params[:skill_ids].nil?
      

      if resource.active_for_authentication?
        set_flash_message :notice, :signed_up if is_flashing_format?
        sign_up(resource_name, resource)
        respond_with resource, location: after_sign_up_path_for(resource)
      else
        set_flash_message :notice, :"signed_up_but_#{resource.inactive_message}" if is_flashing_format?
        expire_data_after_sign_in!
        respond_with resource, location: after_inactive_sign_up_path_for(resource)
      end
    else
      @skills = Skill.all
      clean_up_passwords resource
      respond_with resource
    end  
  end

  def after_inactive_sign_up_path_for(resource)
    @skills = Skill.all
    respond_to?(:root_path) ? root_path : "/"
  end



  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:admin_privileges, :role, :name, :phone_number, :grade, :birthday, :badges, :profile_photo, :email, :password, :password_confirmation) }
  end

  def skills_params
    params.require(:user).permit(:skill_ids => [], :descriptions => [])
  end

  def troop_ids_param
    params.require(:user).permit(:troops_ids => [])
  end


  private
  def sanitize_params_by_role
    if params[:user][:role] != "Scout"
      params[:user][:birthday] = nil
      params[:user][:grade] = nil
    # else  
      # params[:user][:skill_ids].clear
    end
    if 
      params[:user][:role] == "Troop Leader"
      params[:user][:admin_privileges] = 0
    end
  end


end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  def new
    self.resource = resource_class.new(sign_in_params)
    clean_up_passwords(resource)
    if ((@_lookup_context.instance_values["details"][:formats]).length>1)#this condition is met when and only when action is called from modal. It is unclear if this will always be the case though. 
      respond_with(resource, serialize_options(resource))
    else
       respond_with(resource, serialize_options(resource)) do |format|
        format.html { render action: "new_full_page"}
      end
     # respond_with(resource, serialize_options(resource))
    end
  end
end

app/controllers/users/users_controller.rb
class UsersController < ApplicationController
  before_filter :login_required

  before_action :set_user, only: [:show, :edit, :update, :destroy]

  def login_required
     authenticate_user!    
  end
  
  def index
    @troop = Troop.find(params[:troop_id])
    @users = @troop.users
  end

  # def new
  #   raise inspect.params
  #   # @troop = Troop.find_by(params[:troop_id])
  #   @user = User.new
  #   # @scouts = Scout.find(params[:troop_id])

  # end

  # def create
  #   @troop = Troop.find(params[:troop_id])
  #   @scout = @troop.scouts.new(scout_params) #associates scout with that troop
  #   respond_to do |format|
  #     if @scout.save
  #       format.html { redirect_to troops_path, notice: 'Scout was successfully created.' }
  #     else
  #       format.html { render action: 'new' }
  #     end
  #   end
  # end

  def show
  end

  def edit
  end

  def update
  end

  def destroy
  end

  private
  def set_user
    @user = User.find(params[:id])
  end


  # def scout_params
  #   params.require(:scout).permit(:name, :troop_id, :grade, :birthday, :email, :phone_number, :admin_privileges, :dues, :profile_photo, :patches)
  # end
end

app/helpers/users_helper.rb
module UsersHelper

  def add_skills_to_adults(user_id, skill_ids, skill_descriptions)
    skill_ids.each do |skill_id|
      UserSkill.create(skill_id: skill_id, user_id: user_id, skill_description: skill_descriptions[skill_id.to_i - 1])
    end
  end

  def add_comma_seperated_skills_to_adults(user_id, skill_ids, skill_descriptions)
    skill_ids.each do |skill_id|
      if skill_descriptions[skill_id.to_i - 1] != ""
        skill_descriptions[skill_id.to_i - 1].split(",").each do |skill_description|
          UserSkill.create(skill_id: skill_id.to_i, user_id: user_id, skill_description: skill_description)
        end
      else
        UserSkill.create(skill_id: skill_id.to_i, user_id: user_id, skill_description: skill_descriptions[skill_id.to_i - 1])
      end
    end
  end

  def remove_skills(user_skill_ids)
    user_skill_ids.each do |user_skill_id|
      UserSkill.find(user_skill_id.to_i).destroy
    end
  end

  def placeholder(skill_name)
    case skill_name
    when "Music"
      "Viola, Piano, Flute"
    when "Health & Safety"
      "CPR, Bike Safety"
    when "Cooking"
      "Baking, Stir Fry, BBQ"
    when "Outdoor Skills"
      "Camping, Fishing, Hunting"
    when "Arts & Crafts"
      "Origami, Painting"
    when "Math"
      "Division, Algebra, Statistics"
    when "Computer Science"
      "Ruby on Rails, HTML"
    when "Sports & Fitness"
      "Basketball, Kickbox"
    when "Drama"
      "Theatre, Set"
    when "Dance"
      "Tap, Breakdance, Ballet"
    when "Geography & Culture"
      "Maps, Anthropology"
    when "Community Service"
      "Volunteer Work, Finding Need"
    when "Technology"
      "Computers, Microwaves"
    when "Engineering"
      "Electrical, Mechanical"
    when "Science"
      "Biology, Chemistry"
    when "Astronomy"
      "Planetary Rotations"
    when "Financial Literacy"
      "Investment Strategies, Calculating Tips"
    when "Career Exploration"
      "Interviews, Job Search"
    when "Plants & Gardening"
      "Farming, Home Garden"
    when "Animals"
      "Wild, Domestic, Amphibians"
    when "Climate/Earth Science"
      "Geology, Recycling"
    when "Habitat Restoration"
      "Animal Habitats"
    when "OTHER"
      "Parkour, Marketing"
    #for additional functionality
    when "Folk Dance & Games"
      "Salsa, Chess"
    when "Sewing, Needle Arts"
      "Knitting, Crochet"
    when "Other"
      "Parkour, Marketing"
    when "Nature, Ecology"
      "Bird Watching, Recycling"
    when "Photography"
      "Black & White, Still Life, SLR"


    end

  end

  def grade_level
    [
      ['Kindergarten'],
      ['1st'],
      ['2nd'],
      ['3rd'],
      ['4th'],
      ['5th'],
      ['6th'],
      ['7th'],
      ['8th'],
      ['9th'],
      ['10th'],
      ['11th'],
      ['12th'],
    ]
  end

end

app/views/users/edit.html.erb
<%=render partial: 'layouts/banner', locals: {:name => "Edit Account", :left_option => "Troop Hub: The Social Media Site for Girl Scouts", :right_option => "Edit Your Account" }%>
<div class="inner-page padd">
  <!-- Booking Start -->
  <div class="booking">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <!-- Heading -->
          <h3 >Edit Account</h3>
          </div> <!-- col-md-12 -->
          <!-- Image Slider -->
          <div class="col-md-4">
          <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
          <!-- Wrapper for slides -->
            <div class="carousel-inner">
              <div class="item active">
                <img class="img-responsive" src="<%= asset_path("gs_cookie1.jpg") %>" alt="" />
              </div>
              <div class="item">
                <img class="img-responsive" src="<%= asset_path("gs_cookie2.jpg") %>" alt="" />
              </div>
              <div class="item">
                <img class="img-responsive" src="<%= asset_path("gs_cookie3.jpg") %>" alt="" />
              </div>
              <div class="item">
                <img class="img-responsive" src="<%= asset_path("gs_cookie4.jpg") %>" alt="" />
              </div>
              <div class="item">
                <img class="img-responsive" src="<%= asset_path("gs_cookie5.jpg") %>" alt="" />
              </div>
            </div> <!-- carousel-inner -->
            <!-- Controls -->
            <a class="left carousel-control" href="#carousel-example-generic" data-slide="prev">
              <span class="fa fa-chevron-left"></span>
            </a>
            <a class="right carousel-control" href="#carousel-example-generic" data-slide="next">
              <span class="fa fa-chevron-right"></span>
            </a>
          </div> <!-- carousel-example-generic -->
        </div> <!-- col-md-4 -->
        <div class="col-md-8">
          <!-- Booking form without skills sections-->
          <div class="col-md-5">
            <% if flash[:notice] %>
              <div id=”notice” class="alert alert-danger" background-color = red><%= flash[:notice] %></div>
            <% end %>
            <%= form_for(:user, url: update_user_path(@user), html: { method: :patch }) do |f| %>
                <!-- Form label -->
                <label>Full Name</label>
                <div class="form-group">
                  <!-- Form input -->
                    <%= f.text_field :name, autofocus: true, :class => "form-control" %>
                </div>
                  <!-- Form label -->
                  <label>Email</label>
                <div class="form-group">
                  <!-- Form input -->
                  <%= f.email_field :email, autofocus: true, :class => "form-control"  %>
                </div>
                <!-- Form label -->
                <div><%=label_tag(:'user[password]', "New Password (leave blank if you don't want to change it)", :class => "form_label_font")%> <i></i><br />
                <%= f.password_field :password, autocomplete: "off" %></div>

                <div><%=label_tag(:'user[password_confirmation]', "Confirm New Password", :class => "form_label_font")%>
                  <br />
                <%= f.password_field :password_confirmation, autocomplete: "off" %></div>
                <br/>
                <br/>
                <% if current_user.admin_privileges < 50 %>
                  <dl><%= f.label :admin_privileges %>:
                  <%= f.select :admin_privileges, User::ADMIN, class: "form-control" %></dl>
                <%end%>
                <!-- Form label -->
                <label>Phone Number</label>
                <div class="form-group">
                  <!-- Form input -->
                  <%= f.text_field :phone_number, autofocus: true, :class => "form-control"  %>
                </div>
                <!-- Form label -->
                <label class="form_label_font">Profile Photo</label>
                <div class="form-group">
                  <!-- Form input -->
                  <%= f.file_field :profile_photo %><br/>
                </div>
                <%=label_tag(:'user[current_password]', "Current Password (we need current password to confirm all changes)", :class => "form_label_font alert-danger")%><br />
                <!-- make this label bigger or bolder or something -->
                <div class="form-group">
                <%= f.password_field :current_password, autocomplete: "off" %>
                </div><br><br>
                <% if @user.role == "Scout"%>
                <div class="col-md-8">
                  <div class="form-group">
                    <%= render :partial => 'users/registrations/scouts_form' , :locals => {:f => f} %>
                <%else%>
                    <%= render :partial => 'users/registrations/adults_form' , :locals => {:f => f, :user => @user} %>
                  <%end%>
                </div><!-- form-group -->
              </div> <!-- col-md-7 -->
 <div class="col-md-7">

<%= f.submit "Update", class: 'btn btn-danger' %>
<% end %>
</div>  
            </div> <!-- booking-form -->
            
        </div> <!-- end col-md-8 -->
            

              


<% if current_user == @user %>
<h3>Cancel my account</h3>

<p>Unhappy? <%= button_to "Cancel my account", registration_path(:user), data: { confirm: "Are you sure?" }, method: :delete, class: 'btn btn-danger'%></p>
<% end %>

  
           <!--  </div> -->
            
          <!-- </div>  --><!-- booking-form -->

      </div> <!-- end row -->
    </div> <!-- end container -->
  </div> <!-- end booking -->
</div> <!-- end inner-page padd -->


<script type="text/javascript">

$(document).ready(function() {

  $('.skills_check_box').change('checkbox :checkbox.toggle', function(e){    
    var skill_id = $(this).data('skill-id');
    var text_field = $('.hidden_skills_text_field#skill_'+skill_id);

    text_field.fadeToggle();
    });

      $('.adults-form').show();

});
</script>

app/views/users/index.html.erb
<%=render partial: 'layouts/banner', locals: {:name => "Our Scouts", :left_option => "Troop Hub: The Social Media Site for Girl Scouts", :right_option => "Check out your Troop" }%>

<center>
  <br>
        
        <div class="chefs padd">
          <div class="container">
            <!-- Default Heading -->
            <div class="row">
              <% @users.each do |user| %>
              <div class="col-md-4 col-sm-4">
                <!-- Chef Member -->
                <div class="chefs-member">
                  <!-- Chefs member header -->
                  <div class="chefs-head">
                    <!-- Member background image -->
                    <img class="chefs-back img-responsive" src="<%= asset_path("page_bg.jpg") %>" alt="" />
                    <!-- chef member image -->
                    <% if user.profile_photo_url %>
                    <a href = "/users/<%=user.id%>"><%= image_tag(user.profile_photo_url(:thumb).to_s, :class => 'chefs-img-index img-responsive')%></a>
                    <% else %>

                    <%= link_to(image_tag('hedwig.jpeg', :class => 'chefs-img-index img-responsive'), user_show_path(@troop, user)) %>
                      <!-- <img src="<%#= asset_path("hedwig.jpeg") %>" class="chefs-img-index img-responsive"> -->
                    <% end %>
                  </div>
                  <!--Name / Heading -->
                  <h3><a href = "/users/<%=user.id%>"><%=user.name%></h3>
                  <!-- Member designation -->
                  <span><a href = "/users/<%=user.id%>"> <%= user.role%></a></span>
                  <!-- Social media links -->
                </div>
              </div>
              <% end %>


          </div>
        </div>
        
        <!-- Chefs End -->

app/views/users/new.html.erb
<h1>New Scouts Form</h1>
<%= render 'form' %>
<%= link_to 'Back', troops_path %>

app/views/users/show.html.erb
<%=render partial: 'layouts/banner', locals: {:name => @user.name, :left_option => "Troop Hub: The Social Media Site for Girl Scouts", :right_option => "Meet Your Troop Members" }%>

<div class="about-company padd">
          <div class="container">
            <div class="row">
              <div class="col-md-2">
                <!-- About Compnay Item -->
                <div class="about-company-item">
                  <!-- About Company Image -->
                  <!-- <img class="img-responsive img-thumbnail" src="img/chef/about-1.jpg" alt="" /> -->
                  <%= image_tag(@user.profile_photo, :class => 'img-responsive img-thumbnail') %>
                </div>
              </div>
              <div class="col-md-6">
                <!-- About Compnay Item -->
                <div class="about-company-item">
                  <!-- Heading -->
                  <h3><span class="lblue"><%=@user.role%></span></h3>
                  <!-- Paragraph -->
                  <% if @user.birthday %>  
                  <p>Birthday: <%= @user.birthday %></p>
                  <% end %> 

                  <% if @user.grade %>  
                  <p>Grade: <%= @user.grade %></p>
                  <% end %>

                  <% if @user.troops.count > 1 %>
                  <p>Troops:</p> <% @user.troops.each do |troop|%>
                    <li><a href = "/troops/<%=troop.id%>"><%=troop.name%></a></li>
                    <%end%>
                    <%elsif @user.troops == 1%>
                    <p>Troop: <a href = "/troops/<%=@user.troop_ids[0]%>"><%=@user.troops[0].name%></a></p>
                    <%end%>

                  <br /><!--/ Line break -->
                  <div class="row">
                
                    <div class="col-md-6 col-sm-6 col-xs-6">
                      <!-- About company inner items -->
                      <div class="about-company-inner">
                        <!-- Paragraph with icon -->

                      <% if @user.role == 'Scout' %>
                      <span class="company-feature"></b>Badges</span>
                       <ul class="list-unstyled">
                        <% @user.badges.each do |badge|%>
                          <li> 
                          <img class = "badge-logo" src = "<%=badge.logo%>"/> <%= badge.name %>  
                          </li>
                        <%end%>

                        <% else %>
                        <span class="company-feature"></b>Skills</span>
                       <ul class="list-unstyled">
                        <% @user.skills.each do |skill|%>
                            <li > <%= skill.name%>
                            <% if @user.user_skills.find_by(skill_id: skill.id).skill_description %>
                             - <span class="lblue">
                            <%=UserSkill.all_descriptions_for(@user.id, skill.id)%>
                             <%#= @user.user_skills.find_by(skill_id: skill.id).skill_description %></span>
                             <% end %>
                            </li>
                          <% end %>
                      <% end %>

                        </ul>
                      </div>
                    </div>
                  </div>

                <% if current_user.role == 'Scout' %>
                  <%#if @user == current_user || current_user.admin_privileges == 0 %>
                    <%= render :partial => 'user_badges/new' %>
                  <%#end%>
                <% end %>

                </div>
              </div>
            </div>
          </div>
        </div>

 
</br>
</br>
<%#= link_to 'Home', troops_path %>
 </center>
 <footer> 
  <center>
 <%= button_to 'Back to Troop', troop_user_path(@troop), method: :get, class: 'btn btn-danger' %>
 </center>
 <br> 
  <center>
  <%if @user == current_user %>
    <%= link_to "Edit Account", edit_user_path, class: "btn btn-danger" %>
  <% elsif current_user.admin_privileges == 0  %>
    <%= link_to "Edit Account", edit_user_path, class: "btn btn-danger" %>    
  <%end%>
  </center>
</footer>