config/routes.rb
Rails.application.routes.draw do

get 'badges' => 'badges#index'
  devise_for :users, controllers: { :registrations => "users/registrations", :invitations => 'users/invitations', sessions: "users/sessions" }

  root 'troops#home'

  get 'newsletters/new' => 'newsletters#new'
  post 'newsletters' => 'newsletters#create'
  get 'newsletters/:id' => 'newsletters#show'

resources :user_badges do
  get :autocomplete_badge_name, :on => :collection
end
resources :events, :only => [:new, :create] do
  get :autocomplete_badge_name, :on => :collection
end



#-------Troop-Specific Routes----------
# get 'user_badges/new' => 'user_badges#new'
# get 'user_badges' => 'user_badges#index'
  #get '/troops' => 'troops#index'
  get 'troops/new' => 'troops#new'
  post '/troops' => 'troops#create'
  get 'troops/search/name' => 'troops#name_search'
  get 'troops/search/location' => 'troops#location_search'
  get 'troops/:id' => 'troops#show', :as => :troop_show

  get '/troops/:troop_id/members' => 'troop_users#index', :as => :troop_user

  # get '/troops' => 'troops#index'
  # get 'troops/new' => 'troops#new'
  # post '/troops' => 'troops#create'

  # get '/troops/:troop_id/users/new' => 'users/invitations#new'
  # post '/troops/:troop_id/users' => 'users#create'
  # get '/troops/:troop_id/users/:id' => 'users#show', 

  #get 'troops/edit/:id' => 'troops#edit'
  #patch 'troops/update/:id' => 'troops#update'

#---Routes for Individual Users -----
  get '/users/:id' => 'users#show', :as => :user_show
  get '/users/edit/:id' => 'users#edit', :as => :edit_user
  patch '/users/update/:id' => 'users#update', :as => :update_user
  delete '/users/destroy' => 'troop_users#destroy'



#-------Events---------------
  get 'events' => 'events#index', :as => :events_index
  get 'events/new'
  get 'events/advanced_search' => 'events#advanced_search'
  get 'events/search' => 'events#search_results'
  get 'events/a_search' => 'events#advanced_search_results'
   get 'events/:id' => 'events#show', :as => :event
  get 'events/:id/edit' => 'events#edit'
  patch 'events/:id' => 'events#update'
  post 'events' => 'events#create'
  delete 'events/:id/delete' => 'events#delete'


  get 'troop_events/new' => 'troop_events#new'
  get 'troop_events/:troop_id/new_event' => 'troop_events#new_event', as: 'new_troop_event'
  post 'troop_events/new_event' => 'troop_events#create_event'
  post 'troop_events' => 'troop_events#create'
  get 'troop_events/:id' => 'troop_events#show', as: 'troop_event'

  post 'photos/:photoable_id/:photoable_type' => 'photos#create'
  delete 'photos/:photoable_id/:page_for_redirect/:photo_id' => 'photos#delete'

  get 'troops/:troop_id/photos' => 'photos#individual_troop', as: 'troop_photos'

  # get '/agenda' => 'agenda#index', :as => :troop_agenda
  # get '/agenda/new' => 'agenda#new', :as => :new_troop_agenda
  # post '/agenda' => 'agenda#create'
  # get '/agenda/:id' => 'agenda#show', :as => :agenda_show
  # get '/agenda/edit/:id' => 'agenda#edit'
  # patch '/agenda/update/:id' => 'agenda#update'
  # delete '/agenda/destroy' => 'agenda#destroy'

  get 'agenda/new' => 'agenda#new'
  post 'agendas' => 'agenda#create'
  get 'agenda/:id' => 'agenda#show', as: 'agenda_show'
  get 'agenda' => 'agenda#index'

    
  get 'skills' => 'skills#index'
  get 'skills/:id/index' => 'skills#category_index'
  get 'skills/:id'  => 'skills#show'

  #-------Troop Blog---------------
  get '/troops/:id/troop_blog/new' => 'troop_blogs#new',  :as => 'troop_blog_new'
  post '/troops/:id/troop_blogs' => 'troop_blogs#create', :as => 'troop_blogs'
  get 'troops/:id/troop_blog' => 'troop_blogs#index', :as => 'troop_blog_index'


end

app/models/skill.rb
class Skill < ActiveRecord::Base
   has_many :user_skills
   has_many :users, through: :user_skills

   has_many :events
end

app/controllers/skills_controller.rb
class SkillsController < ApplicationController
autocomplete :badge, :name

  def show
    @event = Event.new
    @skills = Skill.order(name: :asc)
    @age_levels = AgeLevel.all
    @badges = Badge.all
    @events = Event.where(:skill_id => params[:id]).order(name: :asc).paginate(page: params[:page], per_page: 10)
    @skill_name = Skill.find(params[:id]).name.upcase
  end

  def category_index    
    @event = Event.new
    @skills = Skill.order(name: :asc)
    @age_levels = AgeLevel.all
    @badges = Badge.all
    @skill_name = params[:id].upcase
    @events = Event.find_by_skill_category( @skill_name).order(name: :asc).paginate(page: params[:page], per_page: 10)
  end
end

app/helpers/skills_helper.rb
module SkillsHelper
end

app/views/skills/_skills.html.erb
 <!-- Page Wrapper -->

    <div class="wrapper">
      <!-- Inner Content -->
      <div class="inner-page padd">
      
        <!-- General Info Start -->
        
        <div class="general">
          <div class="container">
            <div class = "default-heading">
             <!--  <img class = "img-responsive" src =  alt> -->
              <%= image_tag "gs2-white.png"%>
              <h2><%=@skill_name%></h2>
              <div class = "border"></div>
            </div>
            <div class="row">
               <div class="col-md-4 col-sm-4">
                <!-- General Sidebar image -->
                <div class="component-content">
                  <h4>Search for Events</h4>  
                  <%= render partial: 'events/search'%>
                  <!-- Hot tag -->
                  <br>
                  <%= render partial: 'events/advanced_search'%>
                </div>

                <% if current_user && current_user.admin_privileges == 0 %>
                <div class="component-content">
                  <h3 align="center">Add A New Event</h3>
                  <%= render 'events/form' %>
                  <!-- Hot tag -->
                  <br>

                </div>
                <% else %>
                 <div class="general-img">
                  <img class="img-responsive img-thumbnail" src="/assets/thin_mint_cookie.jpg" alt="" />
                  <!-- Hot tag -->
                 
                </div>
              
                <% end %>
                </div>
                
                
                <!-- General Sidebar image -->
                
              <div class="col-md-8 col-sm-8">
                <!-- General information content -->
                 <% if @events == [] %>
                 <h3> No activities matched your search.<br>  Try using different search terms or browsing activities by category <%= link_to "here.", events_path %></h3>
                 <% end %> 
                 <% @events.each do |event| %>

                  <!-- Navigation tab -->
                  <div class="component-content">
                         
                    <!-- Navigation tabs (Job titles ). Use unique value for "href" in "anchor tags". -->
                     <h3 align="center"><%= event.name %></h3>
                     
                      <!-- List content -->

                      <ul class="list-unstyled" align="center">
                        <% unless event.age_levels.empty? %>
                        <li><h5><i class="glyphicon glyphicon-user"></i> Age Levels: 
                           <% event.age_levels.each_with_index do |age_level, i|%>
                            <%if i+1==event.age_levels.length%>
                              <%=age_level.name%>
                            <%else%>
                              <%=age_level.name%>,
                            <%end%>
                          <%end%> 
                        <% end %>
                      
                        </h5></li>
                        <% unless event.badges.empty? %>

                          <li><h5><i class="glyphicon glyphicon-certificate"></i> Badges:                           
                             <% event.badges.each_with_index do |badge, i|%>
                              <%if i+1==event.badges.length%>
                                <%=badge.name%>
                              <%else%>
                                <%=badge.name%>,
                              <%end%>
                            <%end%>                          
                        </h5></li>
                        <% end %>

                        <% unless event.season.blank? %>

                          <li><h5><i class="glyphicon glyphicon-cloud"></i> Seasons:                           
                             <%=event.season%>      
                        </h5></li>
                        <% end %>

                        <% unless event.location.blank? %>

                          <li><h5><i class="glyphicon glyphicon-globe"></i> Location:                           
                             <%=event.location.capitalize%>      
                        </h5></li>
                        <% end %>

                        <% unless event.description.blank? %>

                          <li><h5><i class="glyphicon glyphicon-info-sign"></i> Description:                           
                             <%=event.description%>      
                        </h5></li>
                        <% end %>
                        <% if current_user && current_user.admin_privileges == 0 %>
                        <br>

                        <%= link_to "Add Event to Calendar", troop_events_new_path(:event_id => event.id), class: 'btn btn-danger' %>

                        <% end %>
     
                      </ul>
                    </div><!-- / component content end -->

               <% end %> 
               <%= will_paginate @events, renderer: BootstrapPagination::Rails %>
              <div> <!-- / col-md-8 col-sm-8 end -->

<center>
<%= button_to 'Back To All Events', events_path, method: :get, class: 'btn btn-danger' %></center>  
             

            </div> <!-- / row end -->
          </div> <!-- / container -->
        </div> <!-- / general end -->
        </div> <!-- / inner page pad end -->
        
        <!-- General Info End -->
      
        
      </div><!-- / Inner Page Content End --> 
      
     
      
    </div><!-- / Wrapper End -->




 

app/views/skills/category_index.html.erb
<%=render partial: 'layouts/banner', locals: {:name => "Events", :left_option => "Troop Hub: The Social Media Site for Girl Scouts", :right_option => "Browse the Events Listed Below and Add them to Your Troop Calendar" }%>
<%= render 'skills/skills' %>

app/views/skills/index.html.erb
<h1>Skills#index</h1>
<p>Find me in app/views/skills/index.html.erb</p>

app/views/skills/show.html.erb
<%=render partial: 'layouts/banner', locals: {:name => "Events", :left_option => "Troop Hub: The Social Media Site for Girl Scouts", :right_option => "Browse the Events Listed Below and Add Them to Your Troop Calendar" }%>

<%= render 'skills/skills' %>