config/routes.rb
Rails.application.routes.draw do

get 'badges' => 'badges#index'
  devise_for :users, controllers: { :registrations => "users/registrations", :invitations => 'users/invitations', sessions: "users/sessions" }

  root 'troops#home'

  get 'newsletters/new' => 'newsletters#new'
  post 'newsletters' => 'newsletters#create'
  get 'newsletters/:id' => 'newsletters#show'

resources :user_badges do
  get :autocomplete_badge_name, :on => :collection
end
resources :events, :only => [:new, :create] do
  get :autocomplete_badge_name, :on => :collection
end



#-------Troop-Specific Routes----------
# get 'user_badges/new' => 'user_badges#new'
# get 'user_badges' => 'user_badges#index'
  #get '/troops' => 'troops#index'
  get 'troops/new' => 'troops#new'
  post '/troops' => 'troops#create'
  get 'troops/search/name' => 'troops#name_search'
  get 'troops/search/location' => 'troops#location_search'
  get 'troops/:id' => 'troops#show', :as => :troop_show

  get '/troops/:troop_id/members' => 'troop_users#index', :as => :troop_user

  # get '/troops' => 'troops#index'
  # get 'troops/new' => 'troops#new'
  # post '/troops' => 'troops#create'

  # get '/troops/:troop_id/users/new' => 'users/invitations#new'
  # post '/troops/:troop_id/users' => 'users#create'
  # get '/troops/:troop_id/users/:id' => 'users#show', 

  #get 'troops/edit/:id' => 'troops#edit'
  #patch 'troops/update/:id' => 'troops#update'

#---Routes for Individual Users -----
  get '/users/:id' => 'users#show', :as => :user_show
  get '/users/edit/:id' => 'users#edit', :as => :edit_user
  patch '/users/update/:id' => 'users#update', :as => :update_user
  delete '/users/destroy' => 'troop_users#destroy'



#-------Events---------------
  get 'events' => 'events#index', :as => :events_index
  get 'events/new'
  get 'events/advanced_search' => 'events#advanced_search'
  get 'events/search' => 'events#search_results'
  get 'events/a_search' => 'events#advanced_search_results'
   get 'events/:id' => 'events#show', :as => :event
  get 'events/:id/edit' => 'events#edit'
  patch 'events/:id' => 'events#update'
  post 'events' => 'events#create'
  delete 'events/:id/delete' => 'events#delete'


  get 'troop_events/new' => 'troop_events#new'
  get 'troop_events/:troop_id/new_event' => 'troop_events#new_event', as: 'new_troop_event'
  post 'troop_events/new_event' => 'troop_events#create_event'
  post 'troop_events' => 'troop_events#create'
  get 'troop_events/:id' => 'troop_events#show', as: 'troop_event'

  post 'photos/:photoable_id/:photoable_type' => 'photos#create'
  delete 'photos/:photoable_id/:page_for_redirect/:photo_id' => 'photos#delete'

  get 'troops/:troop_id/photos' => 'photos#individual_troop', as: 'troop_photos'

  # get '/agenda' => 'agenda#index', :as => :troop_agenda
  # get '/agenda/new' => 'agenda#new', :as => :new_troop_agenda
  # post '/agenda' => 'agenda#create'
  # get '/agenda/:id' => 'agenda#show', :as => :agenda_show
  # get '/agenda/edit/:id' => 'agenda#edit'
  # patch '/agenda/update/:id' => 'agenda#update'
  # delete '/agenda/destroy' => 'agenda#destroy'

  get 'agenda/new' => 'agenda#new'
  post 'agendas' => 'agenda#create'
  get 'agenda/:id' => 'agenda#show', as: 'agenda_show'
  get 'agenda' => 'agenda#index'

    
  get 'skills' => 'skills#index'
  get 'skills/:id/index' => 'skills#category_index'
  get 'skills/:id'  => 'skills#show'

  #-------Troop Blog---------------
  get '/troops/:id/troop_blog/new' => 'troop_blogs#new',  :as => 'troop_blog_new'
  post '/troops/:id/troop_blogs' => 'troop_blogs#create', :as => 'troop_blogs'
  get 'troops/:id/troop_blog' => 'troop_blogs#index', :as => 'troop_blog_index'


end

app/models/event.rb
require 'prime'

class Event < ActiveRecord::Base

  has_many :troop_events
  has_many :troops, through: :troop_events

  has_many :event_badges, dependent: :destroy
  has_many :badges, through: :event_badges, dependent: :destroy

  has_many :event_age_levels, dependent: :destroy
  has_many :age_levels, through: :event_age_levels, dependent: :destroy
  belongs_to :skill

  validates :name, :presence => true 
  validates :skill_id, :presence => true
  validates :season, :presence => true


  def self.find_all_by_name(name)
    where("name like ?", name)
  end

  def self.find_by_search_results_with_too_many_forks(name, skill_id, age_level_ids, badge_ids, season_number)
    seasons = Event.seasons_for_search(season_number.to_i)
    skills = Event.skills_for_search(skill_id)
    badges = Event.badges_for_search(badge_ids)
    ages = Event.ages_for_search(age_level_ids) if age_level_ids

    if (name != "") && seasons.nil? && skills.nil? && age_level_ids.nil? && badge_ids.nil?
      results = Event.find_all_by_name(name.capitalize)
    elsif age_level_ids && (badge_ids != []) && (name != "")
      results = Event.all.joins(:event_age_levels).where(:"event_age_levels.age_level_id" => ages).joins(:event_badges).where(:"event_badges.badge_id" => badges).where("name like ?", name).where(season: seasons, skill: skills).uniq
    elsif age_level_ids && (badge_ids != [])
      results = Event.all.joins(:event_age_levels).where(:"event_age_levels.age_level_id" => ages).joins(:event_badges).where(:"event_badges.badge_id" => badges).where(season: seasons, skill: skills).uniq 
    elsif age_level_ids && (name != "")
      results = Event.all.joins(:event_age_levels).where(:"event_age_levels.age_level_id" => ages).where("name like ?", name).where(season: seasons, skill: skills).uniq
    elsif age_level_ids
      results = Event.all.joins(:event_age_levels).where(:"event_age_levels.age_level_id" => ages).where(season: seasons, skill: skills).uniq 
    elsif (badge_ids != []) && (name != "")
      results = Event.all.joins(:event_badges).where(:"event_badges.badge_id" => badges).where("name like ?", name).where(season: seasons, skill: skills).uniq
    elsif (badge_ids != [])
      results = Event.all.joins(:event_badges).where(:"event_badges.badge_id" => badges).where(season: seasons, skill: skills).uniq 
    elsif (name != "")
      results = Event.where("name like ?", name).where(season: seasons, skill: skills).uniq
    else
      results = Event.where(season: seasons, skill: skills).uniq
    end
    results
  end

  def self.seasons_for_search(searched_season_number)
    seasons = {1 => 'Any', 2 => 'Spring', 3 => 'Summer', 5 => 'Fall', 7 => 'Winter', 49 => 'January', 77 => 'Febuary', 14 => 'March', 4 => 'April', 22 => 'May', 6 => 'June', 9 => 'July', 33 => 'August', 15 => 'September', 25 => 'October', 55 => 'November', 35 => 'December', 245 => 'New Years', 117 => 'Independence Day'}
    season_array = []
    seasons.each do |season_number, season_name|
      if searched_season_number % season_number == 0 || season_number % searched_season_number == 0
        season_array << season_name
      end
    end
    season_array
  end

  def self.badges_for_search(names)
    ids = []
    names.each do |name|
      b = Badge.find_by(name: name)
      ids<< b.id
    end
    ids
  end

  def self.ages_for_search(ages)
    if ages.include?(7.to_s)
      (1...7).each do |x|
        ages << x
      end
    else
      all = true
      (1...7).each do |i|
        if not ages.include?(i.to_s)
          all = false
        end
      end
      if all
        ages << 7
      end
    end
    ages
  end


  def self.skills_for_search(skill_id)
    if skill_id.to_i > 0
      skills = Skill.where(id: skill_id)
    elsif skill_id == "General"
      skills = Skill.where(category: 'GENERAL')
    elsif skill_id == "STEM"
      skills = Skill.where(category: 'STEM')
    elsif skill_id == 'Business Smarts'
      skills = Skill.where(category: 'BUSINESS SMARTS')
    elsif skill_id == "Nature and Ecology"
      skills = Skill.where(category: 'NATURE AND ECOLOGY')
    else
      skills = Skill.all
    end
    skills
  end

  def self.find_by_skill_category(category_name)
    category_name = category_name.gsub("-and-"," & ").gsub("-"," ")
    Event.joins(:skill).where("skills.category like ?", category_name.upcase)
  end


  def self.header_for_advanced_search_results(search_criteria)
    header = "Events"
    if (search_criteria[:name] != "")
      header += " named #{search_criteria[:name]}"
    end
    if (search_criteria[:skill_id].to_i != 0)
      skill = Skill.find(search_criteria[:skill_id]).name
      header += " related to #{skill}"
    elsif (search_criteria[:skill_id] != "Any")
      header += " related to #{search_criteria[:skill_id]}"
    else
      header += " related to Any Category"
    end
    if (search_criteria[:age_level_ids])
      ages = " for"
      search_criteria[:age_level_ids].each_with_index do |age_level_id, i|
        if (i == 0)
          name = AgeLevel.find(age_level_id).name
          ages+= " #{name.pluralize}"
        else
          name = AgeLevel.find(age_level_id).name
          ages+= " or #{name.pluralize}"
        end
      end
      header += "#{ages}"
    end
      header += Event.seasons_for_header(search_criteria[:season])
    if (search_criteria[:badge_ids] != "")
      badges = Event.badges_for_search_result_header(search_criteria[:badge_ids])
      header += " giving #{badges}"
    end
    header
  end

  def self.badges_for_search_result_header(badge_names)#this method and one above should be in controller
    badge_names_array = badge_names.split(",") #this and next three lines of code is taken from create event controller. This should either be abstraced or ask emma if autocomplete will allow us to save data from this field in array
    badge_string = ""
    badge_names_array.each_with_index do |b, i|
      if (i == (badge_names_array.length - 1) && badge_names_array.length != 1 && badge_names_array.length != 2)
        badge_string += "or #{b} badges"
      elsif (badge_names_array.length != 1 && badge_names_array.length != 2)
        badge_string += "#{b}, "
      elsif  badge_names_array.length != 2
        badge_string += "a #{b} badge"
      elsif i != (badge_names_array.length - 1)
        badge_string+=b
      else
        badge_string += " or #{b} badges"
      end
    end
    " badges"
    badge_string
  end

  def self.seasons_for_header(number)
    seasons = ""

    lookup_hash = {1 => 'Any', 2 => 'Spring', 3 => 'Summer', 5 => 'Fall', 7 => 'Winter', 49 => 'January', 77 => 'Febuary', 14 => 'March', 4 => 'April', 22 => 'May', 6 => 'June', 9 => 'July', 33 => 'August', 15 => 'September', 25 => 'October', 55 => 'November', 35 => 'December', 245 => 'New Years', 117 => 'Independence Day'}
    number = number.to_i
    factors = Prime.prime_division(number)
    sum = 0
    factors.each do |array|
        sum+=array[1]
      end
    
    if sum == 0
      seasons+= " during any season"
    elsif sum == 1
      seasons+= " during the #{lookup_hash[number]}"
    elsif sum == 2
      seasons += " in the month of #{lookup_hash[number]}"
    else
      seasons += " on #{lookup_hash[number]}"
    end
    seasons
  end

end

app/models/troop.rb
class Troop < ActiveRecord::Base
   has_many :troop_events
   has_many :events, through: :troop_events

   has_many :troop_users
   has_many :users, through: :troop_users
   
   has_many :photos, as: :photoable
   has_many :newsletters
   has_many :troop_blogs
   belongs_to :age_level

  geocoded_by :full_address
  after_validation :geocode

  mount_uploader :photo, ProfilePhotoUploader


  def on_page_photo
    photos.find_by(:on_page => "true")
  end

  def profile_url
    if url = on_page_photo
      url = url.pic_url
    else
      url = "default_photo.jpg"
    end
    url
  end

  AgeLevel.all.each do |age_level|
    define_singleton_method "all_#{age_level.name}" do
      joins(:age_level).where("age_levels.name = \"#{age_level.name}\" ")
    end
  end

  def full_address
    if city.include?('|')
      cities = city.split('|')
      address = "#{cities[0]}, #{state} #{zip_code}"
    else
      address = "#{city}, #{state} #{zip_code}"
    end
    address
  end

  def self.search_by_name(name)
    where("name like ?", name["name"]).uniq
  end

  def self.search_by_location(location)
    #binding.pry
    near(location["address"])
  end


end

app/controllers/troops_controller.rb
class TroopsController < ApplicationController
  before_action :set_troop, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:new]
  before_action :set_user, only: [:show]

  def index
    @troops = Troop.all
    @daisies = Troop.all_Daisy
    @brownies = Troop.all_Brownie
    @juniors = Troop.all_Junior
    @cadettes = Troop.all_Cadette
    @seniors = Troop.all_Senior
    @ambassadors = Troop.all_Ambassador
    @age_levels = AgeLevel.all
  end

  def show
    @user = current_user
    # @scouts = Scout.where(params[:id])
    @troop_events = TroopEvent.all
    @newsletter = Newsletter.all.last
    @news = TroopBlog.troop_news_feed(params[:id]).paginate(page: params[:page], per_page: 1)
    @sidebar_news = TroopBlog.sidebar_news_feed(params[:id])
    @troop_events = TroopEvent.all    
  end

  def new
  unless current_user.admin_privileges < 50
    redirect_to(:back)
  end
    @troop = Troop.new 
    @age_levels = AgeLevel.all
  end

  def create
    @troop = Troop.create(troop_params)
    @troop.user_ids = current_user.id
    @age_levels = AgeLevel.all

    respond_to do |format|
      if @troop.save
        format.html { redirect_to troop_show_path(@troop), notice: 'Troop was successfully created.' }
      else
        @age_levels = AgeLevel.all
        format.html { render action: 'new' }
      end
    end
  end

  def name_search
    if params[:troop]
      @troops = Troop.search_by_name(params[:troop])
    else
      redirect_to ("/")
    end
  end

  def location_search
    if params[:troop]
      @troops = Troop.search_by_location(params[:troop])
    else
      redirect_to ("/")
    end
  end

  def home
    @age_levels = AgeLevel.all
    @badges = Badge.all
    @news = TroopBlog.homepage_news_feed
    @skills = Skill.all
    # @event = Event.new
    # @event_badge = EventBadge.new
    # @troops = Troop.all
    # @events = Event.all
  end


private
  def set_troop
    @troop = Troop.find(params[:id])
  end

  def troop_params
    params.require(:troop).permit(:name, :number, :age_level_id, :city, :state, :zip_code, :meetup_location, :about_us, {:user_ids => [] } )
  end

  def set_user
    @user = User.find(params[:id])
  end

end

app/helpers/troops_helper.rb
module TroopsHelper
end

app/views/troops/_form.html.erb
<%= form_for(@troop) do |f| %>
    <label>Troop Name:</label>
    <%= f.text_field :name, class: "form-control" %></br>
  
    <label>Troop Number:</label>
    <%= f.text_field :number, class: "form-control" %>
  <label>Troop Type:</label></br>
  <% @age_levels.each do |age_level| %>
    <%if age_level.id != 7%>
      <%= f.radio_button :age_level_id, age_level.id%>
      <%= f.label :age_level_id, age_level.name %></br>
    <%end%>
  <% end %>
                      <!-- Form inside table wrapper -->
                     
                    
    <label>City:</label>
    <%= f.text_field :city, class: "form-control" %></br>
  
    <label>State:</label>
    <%= f.text_field :state, class: "form-control" %></br>

  
    <label>Zip Code:</label>
    <%= f.text_field :zip_code, class: "form-control" %></br>

  
    <label>Meetup Location:</label>
    <%= f.text_field :meetup_location, class: "form-control" %></br>

  
    <label>About Us:</label>
      <%= f.text_area :about_us, class: "form-control" %></br>
      <br>

  <button class="btn btn-danger btn-sm show-submit " type="submit">Add Troop</button>
<% end %>

app/views/troops/home.html.erb
<%=render partial: 'layouts/banner', locals: {:name => "troop hub", :left_option => "Troop Hub: The Social Media Site for Girl Scouts", :right_option => "Search Activities, Create Events, and Organize Your Troops! " }%>

    <!-- Page Wrapper -->
    <div class="wrapper">
      <!-- Inner Content -->
      <div class="inner-page padd">
      
        <!-- Blog Start -->
          
        <div class="blog">
          <div class="container">
            <div class="row">
              <div class="col-md-8">
                <!-- The new post done by user's all in the post block -->
                <div class="blog-post">
                  <!-- Entry is the one post for each user -->

                  <% @news.each do |article| %>
                  <div class="entry">
                    <!-- Post Images -->
                    <div class="blog-img pull-left">
                      <img src="<%= article.photo %>" class="img-responsive img-thumbnail" alt="" />
                    </div>
                    <!-- Meta for this block -->
                    <div class="meta">
                      <i class="fa fa-calendar"></i>&nbsp; <%= article.formatted_date %>
                      <span class="pull-right"><i class="fa fa-comment"></i> <a href="/troops/<%=article.troop_id%>"><%= article.find_troop_name(article.troop_id) %></a></span>
                    </div>
                    <!-- Heading of the  post -->
                    <h3><%= link_to article.headline, troop_blog_index_path(article.troop_id) %></h3>
                    <hr /><!-- Horizontal line -->
                    <!-- Paragraph -->
                    <p><%= article.body %></p>
                    <div class="clearfix"></div>
                  </div>
                <% end %>
 
                  
                </div>
              </div> <!--/ Main blog column end -->
              <div class="col-md-4">
                <!-- Blog page sidebar -->
                <div class="blog-sidebar">
                  <div class="row">
                    <div class="col-md-12 col-sm-6">
                      <!-- Blog sidebar page widget -->
                      <div class="sidebar-widget">
                        <!-- Widget Heading -->
                        <h4>Search for Troops</h4>
                        <!-- search button and input box -->
                          <%= render partial: 'troops/search'%>
                      </div><!--/ Widget end -->
                    </div>
                    <div class="col-md-12 col-sm-6">
                      <!-- Blog sidebar page widget -->
                      <div class="sidebar-widget">
                        <!-- Widget Heading -->
                        <h4>Search for Events</h4>
                        <!-- search button and input box -->
                       <%= render partial: 'events/search'%>
                       <br>
                       <center>
                       <%= render partial: 'events/advanced_search'%>
                     </center>
                      </div><!--/ Widget end -->
                    </div>


                    <div class="col-md-12 col-sm-6">
                      <!-- Blog sidebar page widget -->
                      <div class="sidebar-widget">
                   
                       <a class="twitter-timeline" href="https://twitter.com/girlscouts" data-widget-id="455791178433044480">Tweets by @girlscouts</a>
                      <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+"://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>
                      </div><!--/ Widget end -->
                    </div>
                   
                    
                </div><!--/ Page sidebar end -->
              </div>
            </div><!--/ Row end -->
          </div>
        </div>
        
        <!-- Blog End -->   

        
      </div><!-- / Inner Page Content End --> 
      
    
    </div><!-- / Wrapper End -->
    
    
    

app/views/troops/index.html.erb
<center><%=render partial: 'layouts/banner', locals: {:name => "Troops", :left_option => "TBD", :right_option => "TBD" }%>
</div>

<center><h1>Troops</h1>
<% @troops.each do |troop| %>
    <%= link_to troop.name, troop_show_path(troop)%><br>
<% end %>

<br>
<br>
<br>
<center><h3>Daisies</h3>
    <% @daisies.each do |daisy| %>
    <%= link_to daisy.name, troop_show_path(daisy)%>
    <br>
<%end%>
</br>
<center><h3>Brownies</h3>
    <% @brownies.each do |brownie| %>
    <%= link_to brownie.name, troop_show_path(brownie)%>
    <br>
<%end%>
</br>
<center><h3>Juniors</h3>
    <% @juniors.each do |junior| %>
    <%= link_to junior.name, troop_show_path(junior)%>
    <br>
<%end%>
</br>
<center><h3>Cadettes</h3>
    <% @cadettes.each do |cadette| %>
    <%= link_to cadette.name, troop_show_path(cadette)%>
    <br>
<%end%>
</br>
<center><h3>Seniors</h3>
    <% @seniors.each do |senior| %>
    <%= link_to senior.name, troop_show_path(senior)%>
    <br>
<%end%>
</br>
<center><h3>Ambassadors</h3>
    <% @ambassadors.each do |ambassador| %>
    <%= link_to ambassador.name, troop_show_path(ambassador)%>
    <br>
<%end%>
</br>

<br>
<%= link_to 'Add Your Troop!', troops_new_path %>

app/views/troops/name_search.html.erb
<%@troops.each do |troop|%>
  <h1><%= link_to troop.name, troop_path(troop) %></h1>
<%end%>

app/views/troops/show.html.erb
<%=render partial: 'layouts/banner', locals: {:name => @troop.name, :left_option => "Troop Hub: The Social Media Site for Girl Scouts", :right_option => "Troop Number: #{@troop.number}" }%>
<!-- #update! -->
    <!-- if we want to be really snazzy we should change the word "company" to "troop" here and in the css file -->
<div class="about-company padd">
    <div class="container">
        <div class="row">
            <div class="col-md-6">
                <div class="about-company-item"> 
                    <%= image_tag @troop.profile_url, :class =>  "img-responsive img-thumbnail"%>
                </div>
            </div>
            <div class="col-md-6">
                <div class="about-company-item">
                    <h3>About Us:</h3>
                    <p><%=@troop.about_us %></p>
                    </br>
                </div> 
            </div> <!-- end col-md-6 -->
        </div> <!-- end row -->


<!-- hide from non Troop members -->
 <% if @user && @user.troop_ids.include?(@troop.id)%>
<div class="showcase">
          <div class="container">
            <div class="row">
              <div class="col-md-6 col-sm-6">
                <!-- Showcase section item -->
                <div class="showcase-item">
                  <!-- Image -->
                  <img class="img-responsive" src="/assets/making_friends.gif" alt="" />
                  <!-- Heading -->
                  <h3><%= link_to 'Meet Your Troop!', troop_user_path(@troop) %></h3>
                  <!-- Paragraph -->
                  <p>View the members of your troop and add our virtual badges to your profile page.</p>
                  <div class="clearfix"></div>
                </div>
              </div>
              <div class="col-md-6 col-sm-6">
                <!-- Showcase section item -->
                <div class="showcase-item">
                  <!-- Image -->
                  <img class="img-responsive" src="/assets/activity_badge.gif" alt="" />
                  <!-- Heading -->
                  <h3><%= link_to 'Browse Activities', events_path %></br></h3>
                  <!-- Paragraph -->
                  <p>Browse the activities in our database and help plan the next event for your troop!</p>
                  <div class="clearfix"></div>
                </div>
              </div>
            </div>`
          </div>
        </div>
        <%end%>

<br/>
<br/>

</br>
</br>
<%#= link_to 'Add a scout', new_troop_scout_path %>
</br>
</br>
<div class="row">
<div class="col-md-">
    <div class="panel-group" id="accordion">
      <div class="panel panel-default" width= "100px">
        <div class="panel-heading">
          <h4 class="panel-title">
            <a data-toggle="collapse" data-parent="#accordion" href="#cal">
               <center>Calendar of Events </center>
            </a>
          </h4>
        </div>
        <div id="cal" class="panel-collapse collapse in">
          <div class="panel-body">

      <%= calendar @troop_events do |e| %>
    <% if e.troop_id == @troop.id %>

    <li ><a data-toggle="modal" data-target="#<%=e.id%>" href = "#"><%= e.name %></a></li> 

<div class="modal fade" id = "<%=e.id%>" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
 <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title" id="myModalLabel"><center><%=e.name%></center></h4>
      </div>
        <div class="modal-body">
    <center>  
  <b>Date:</b> <%= e.start_time.strftime("%A %B %e")%><br/>
<b>Time:</b> <%= e.start_time.strftime("%I:%M %p") %><br/>
<b>Location:</b> <%= e.location%><br/>
<b>Details:</b> <%= e.detail%><br/></center>
<% if @user.admin_privileges < 50 %>
<center><%= button_to 'Edit', "/troop_events/#{e.id}/edit", method: :get, class: 'btn btn-danger' %></center>
<center><%= button_to 'Delete', "/troop_events/#{e.id}", method: :delete, class: 'btn btn-danger' %></center>
  <%end%>
  <%end%>
  </div>
</div>
  <%end%>
   </div>
  </div>
</div>

    </div>
    </div>
    </div>
  <div class="col-md-">
    <div class="panel-group" id="accordion">
      <div class="panel panel-default" width="100px">
        <div class="panel-heading">
          <h4 class="panel-title">
            <a data-toggle="collapse" data-parent="#accordion" href="#news">
               <center>Troop News</center>
            </a>
          </h4>
        </div>
            <div id="news" class="panel-collapse collapse in">
          <div class="panel-body">
        <!-- Inner Content -->
      <div class="inner-page padd">
      
        <!-- Blog Start -->
          
        <div class="blog">
          <div class="container">
            <div class="row">
              <div class="col-md-8">
                <!-- The new post done by user's all in the post block -->
                <div class="blog-post">
                  <!-- Entry is the one post for each user -->
                <% if @news == [] %>
                  <h4> You haven't posted any news yet. </h4>
                  <h4><%= link_to "Add More News Here >>", troop_blog_new_path(@troop) %></h4>
                <% else %>
                  <% @news.each do |article| %>
                    <div class="entry">
                      <!-- Post Images -->
                      <div class="blog-img pull-left">
                        <img src="<%= article.photo %>" class="img-responsive img-thumbnail" alt="" />
                      </div>
                      <!-- Meta for this block -->
                      <div class="meta">
                        <i class="fa fa-calendar"></i>&nbsp; <%= article.formatted_date %>
                        <span class="pull-right"><i class="fa fa-comment"></i> <a href="/troops/<%=article.troop_id%>"><%= article.find_troop_name(article.troop_id) %></a></span>
                      </div>
                      <!-- Heading of the  post -->
                      <h3><%= link_to article.headline, troop_blog_index_path(@troop) %></h3>
                      <hr /><!-- Horizontal line -->
                      <!-- Paragraph -->
                      <p><%= article.body %></p>
                      <p><%= link_to 'Continue reading more news articles', troop_blog_index_path(@troop) %></p>
                      <div class="clearfix"></div>
                    </div>
                  <% end %>
                <% end %>
 
                  <!-- Entry is the one post for each user -->


                  <!-- Pagination -->
          
                  <!-- Pagination end-->
                </div>
              </div> <!--/ Main blog column end -->
              <div class="col-md-3">
                <!-- Blog page sidebar -->
                <div class="blog-sidebar">
                  
                    <div class="col-md-12 col-sm-6">
                      <!-- Blog sidebar page widget -->
                      <div class="sidebar-widget">
                        <!-- Widget Heading -->
                        <h4>Recent Posts</h4>
                        <!-- Recent post list -->
                        <ul class="list-unstyled">
                          <% @sidebar_news.each do |article|  %>
                          <li><i class="fa fa-angle-double-right"></i> <%= link_to "#{article.headline}", troop_blog_index_path(@troop) %></li>
                          <% end %>
                        </ul>
                      </div><!--/ Widget end -->
                    </div>
                   
                  </div><!--/ Inner row end -->
                </div><!--/ Page sidebar end -->
              </div>
            </div><!--/ Row end -->

        
        <!-- Blog End -->
        <!-- <div id="collapseOne" class="panel-collapse collapse in">
          <div class="panel-body">
            <%# unless @newsletter.nil? %>
                <%#= render partial: 'newsletters/show' %>
                <%# end %>
<%# if current_user && current_user.admin_privileges < 50 %>
<left><%#=link_to 'Update News Section', newsletters_new_path %></left>
<%#end%>
                <br/>
          </div>
        </div> -->
      </div>
    </div>
    </div>

      </div>
</div>
    </div> <!-- container -->
</div> <!-- end about-company padd -->